apiVersion: v1
data:
  database-name: c29uYXI=
  database-password: c29uYXI=
  database-user: c29uYXI=
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: postgresql-persistent
    template: postgresql-persistent-template
  name: postgresql
type: Opaque
